name: brew-bump-packages
on:
  workflow_dispatch

jobs:
  foo:
    runs-on: [macos-13]
    steps:
      - name: Bump packages
        uses: dawidd6/action-homebrew-bump-formula@v3
        with:
          # Custom GitHub access token with the 'public_repo' and 'workflow' scopes enabled
          token: ${{secrets.TOKEN}}
          tap: shaunplee/asic
          # Bump only these formulae if outdated
          formula: magic-vlsi, tcl-tk-with-x
          livecheck: true
